ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkFaUDy0yBjUmnPkLYgTfPuwcjlkRFTUic7ZP6qOSnq767/gEhCcQkIwWXWh2uIuP/A/zN84bF+NP9BH6lLz3hGW5jTFE+VzUXoXonGMrHtB0s1jw0F+3EXMW8pJAUt24Dr/Vo1ic4UIadGhcSzadRXWHEnbGU70xAbMalc/gk0xzN4rH5rajERo8rzyubjGxa/v2oN+p/kzdk4W4zJa02tvt0mN+vGmx93R06CaFEn9he7pt+tOzKfa76y/NiQB9ojSwbJbigdQ8hEMigDk9Nmm3vevmas6NTPGdLiQhJLWDIWCzsSb2lnua3PpUhfoCktEOMAxr+qtrQzrpZ1al8Q== rsa-key-20170718
- github:janci78

k3os:
  data_sources:
  - aws
  - cdrom
  modules:
  - kvm
  - nvme
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: P@ssw0rd
